from ._generated_constants import (
    DEFAULT_AUTH_URL,
    AUTH_TOKEN_PATH,
    AUTH_REFRESH_PATH,
    WS_SUBPROTOCOL,
    WS_SUBPROTOCOL_JWT_PREFIX,
    CORTEX_AUTH_URL,
    CORTEX_REFRESH_URL,
    WS_SUBPROTOCOL_BASE,
    SCHEMA_VERSION,
    DEFAULT_CONNECT_TIMEOUT_MS,
    DEFAULT_SEND_TIMEOUT_MS,
    DEFAULT_RESYNC_TIMEOUT_MS,
    DEFAULT_PING_INTERVAL_MS,
    DEFAULT_PONG_TIMEOUT_MS,
    DEFAULT_STALE_THRESHOLD_MS,
    TOKEN_REFRESH_BUFFER_MS,
    RECONNECT_BACKOFF_MS,
)

__all__ = [
    "DEFAULT_AUTH_URL",
    "AUTH_TOKEN_PATH",
    "AUTH_REFRESH_PATH",
    "WS_SUBPROTOCOL",
    "WS_SUBPROTOCOL_JWT_PREFIX",
    "CORTEX_AUTH_URL",
    "CORTEX_REFRESH_URL",
    "WS_SUBPROTOCOL_BASE",
    "SCHEMA_VERSION",
    "DEFAULT_CONNECT_TIMEOUT",
    "DEFAULT_SEND_TIMEOUT",
    "DEFAULT_RESYNC_TIMEOUT",
    "DEFAULT_PING_INTERVAL",
    "DEFAULT_PONG_TIMEOUT",
    "DEFAULT_STALE_THRESHOLD",
    "TOKEN_REFRESH_BUFFER",
    "RECONNECT_BACKOFF",
]


DEFAULT_CONNECT_TIMEOUT: float = DEFAULT_CONNECT_TIMEOUT_MS / 1000
DEFAULT_SEND_TIMEOUT: float = DEFAULT_SEND_TIMEOUT_MS / 1000
DEFAULT_RESYNC_TIMEOUT: float = DEFAULT_RESYNC_TIMEOUT_MS / 1000
DEFAULT_PING_INTERVAL: float = DEFAULT_PING_INTERVAL_MS / 1000
DEFAULT_PONG_TIMEOUT: float = DEFAULT_PONG_TIMEOUT_MS / 1000
DEFAULT_STALE_THRESHOLD: float = DEFAULT_STALE_THRESHOLD_MS / 1000
TOKEN_REFRESH_BUFFER: float = TOKEN_REFRESH_BUFFER_MS / 1000

RECONNECT_BACKOFF: list[float] = [value / 1000 for value in RECONNECT_BACKOFF_MS]
